commit to hw2
ChernykhGO/nodejs-homework-rest-api pull request #1
Opened 2021-11-09 20:20 UTC by ChernykhGO

Без ошибки валидации

2021-11-11 15:36 UTC, TViglesGoom requested changes

2021-11-11 15:36 UTC, TViglesGoom commented on model/index.js
> +  const idx = contacts.findIndex((item) => item.id === Number(contactId));
Ну я бы ещё понял каст к String, но к Number? У вас же айдишник всех новых контактов это строка. В 17 и 46 строках тоже самое.

2021-11-11 15:36 UTC, TViglesGoom commented on routes/api/contacts.js
> +    // }
Это что?

2021-11-12 19:48 UTC, ChernykhGO commented on model/index.js
> +  const idx = contacts.findIndex((item) => item.id === Number(contactId));
исправила, привела к строке

2021-11-14 11:05 UTC, TViglesGoom approved these changes

2021-11-14 13:27 UTC, merged