Hw03
ChernykhGO/nodejs-homework-rest-api pull request #2
Opened 2021-11-21 19:56 UTC by ChernykhGO

Added hw3

2021-11-21 21:40 UTC, KirillKulakow commented on controllers/contacts/add.js
> +  console.log(req.body);
удалить

2021-11-21 21:41 UTC, KirillKulakow commented on controllers/contacts/updateById.js
> +  console.log(result);
удалить

2021-11-21 21:42 UTC, KirillKulakow commented on controllers/contacts/updateFavorite.js
> +  console.log(result);
удалить

2021-11-21 21:43 UTC, KirillKulakow commented on middlewares/controllerWrapper.js
> +const controllerWrapper = (ctrl) => {
можно использовать замыкания = (ctrl) => (req, res, next) => {}

2021-11-21 21:44 UTC, KirillKulakow commented on middlewares/validation.js
> +      // const newError = new BadRequest(error.message);
если не используешь - удалить + первые строки

2021-11-21 21:45 UTC, KirillKulakow requested changes
Need fix

2021-11-22 20:22 UTC, ChernykhGO commented
cleared the code

2021-11-22 20:38 UTC, KirillKulakow approved these changes

2021-11-22 21:03 UTC, merged