Hw04 auth
ChernykhGO/nodejs-homework-rest-api pull request #3
Opened 2021-11-29 20:06 UTC by ChernykhGO

2021-11-29 22:36 UTC, KirillKulakow commented on controllers/contacts/getById.js
> +  const result = await Contact.findById(contactId)
добавить поиск оп собственнику

2021-11-29 22:36 UTC, KirillKulakow commented on controllers/contacts/removeById.js
> +  const result = await Contact.findOneAndRemove(contactId)
добавить поиск оп собственнику

2021-11-29 22:36 UTC, KirillKulakow commented on controllers/contacts/updateById.js
>    const result = await Contact.findByIdAndUpdate(contactId, req.body, {
добавить поиск оп собственнику

2021-11-29 22:36 UTC, KirillKulakow commented on controllers/contacts/updateFavorite.js
>    const result = await Contact.findByIdAndUpdate(
добавить поиск оп собственнику

2021-11-29 22:36 UTC, KirillKulakow commented on middlewares/authenticate.js
> +  console.log(req.headers.authorization);
удалить

2021-11-29 22:37 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
если authorization будет undefined - будет ошибка

2021-11-29 22:38 UTC, KirillKulakow commented on routes/api/auth.js
> +router.get("/logout", authenticate, controllerWrapper(ctrl.logout));
пропущен один шаг из дз

2021-11-29 22:38 UTC, KirillKulakow requested changes
need fix

2021-12-02 20:26 UTC, KirillKulakow commented on controllers/contacts/updateById.js
> +  const result = await Contact.findByIdAndUpdate(
findById с двумя ид не будет работать findOne

2021-12-02 20:26 UTC, KirillKulakow commented on controllers/contacts/updateFavorite.js
>    const result = await Contact.findByIdAndUpdate(
так же

2021-12-02 20:28 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
сделай проверку на то есть ли в headers - authorization!
если нет вернуть ошибку

2021-12-02 20:28 UTC, KirillKulakow requested changes
Need fix

2021-12-04 11:19 UTC, KirillKulakow commented on controllers/contacts/getById.js
> +  console.log(req.params);
удалить

2021-12-04 11:22 UTC, KirillKulakow requested changes
один коммент

2021-12-04 11:43 UTC, ChernykhGO commented
удалила лишнее

2021-12-04 14:55 UTC, merged